import type { PresetCircuit } from "./circuit-types";

export const PRESET_CIRCUITS: PresetCircuit[] = [
  {
    id: "555-timer-flasher",
    title: "NE555 Astable LED Flasher (1 Hz)",
    prompt: "Design an astable NE555 timer circuit that flashes an LED at approximately 1Hz with timing resistors and capacitors",
    category: "Oscillator & Timing",
    json: {
      version: "1.0",
      metadata: {
        name: "NE555 Astable Multivibrator",
        description: "1Hz pulse oscillator driving an output LED indicator with standard timing components",
        powerRequirements: "5V - 12V DC (~15mA)",
        assumptions: ["R1=10k, R2=47k, C1=10uF gives ~1.3 Hz frequency", "0.01uF bypass cap on Pin 5"],
      },
      components: [
        {
          id: "U1",
          type: "ic",
          value: "NE555P",
          description: "Precision Timer IC (DIP-8)",
          pins: [
            { id: "1", name: "GND" },
            { id: "2", name: "TRIG" },
            { id: "3", name: "OUT" },
            { id: "4", name: "RESET" },
            { id: "5", name: "CTRL" },
            { id: "6", name: "THRES" },
            { id: "7", name: "DISCH" },
            { id: "8", name: "VCC" },
          ],
        },
        {
          id: "R1",
          type: "resistor",
          value: "10k",
          description: "Timing Charge Resistor",
          pins: [
            { id: "1", name: "1" },
            { id: "2", name: "2" },
          ],
        },
        {
          id: "R2",
          type: "resistor",
          value: "47k",
          description: "Timing Discharge Resistor",
          pins: [
            { id: "1", name: "1" },
            { id: "2", name: "2" },
          ],
        },
        {
          id: "R3",
          type: "resistor",
          value: "330R",
          description: "LED current limiting resistor",
          pins: [
            { id: "1", name: "1" },
            { id: "2", name: "2" },
          ],
        },
        {
          id: "C1",
          type: "capacitor",
          value: "10uF",
          description: "Electrolytic timing capacitor",
          pins: [
            { id: "+", name: "POS" },
            { id: "-", name: "NEG" },
          ],
        },
        {
          id: "C2",
          type: "capacitor",
          value: "10nF",
          description: "Control voltage noise bypass capacitor",
          pins: [
            { id: "1", name: "1" },
            { id: "2", name: "2" },
          ],
        },
        {
          id: "LED1",
          type: "led",
          value: "Green 5mm",
          description: "Pulse output visual indicator",
          pins: [
            { id: "A", name: "Anode" },
            { id: "K", name: "Cathode" },
          ],
        },
        {
          id: "BT1",
          type: "battery",
          value: "9V Battery Clip",
          description: "DC power supply source",
          pins: [
            { id: "POS", name: "VCC" },
            { id: "NEG", name: "GND" },
          ],
        },
      ],
      connections: [
        { from: "BT1.POS", to: "U1.8" },
        { from: "BT1.POS", to: "U1.4" },
        { from: "BT1.POS", to: "R1.1" },
        { from: "R1.2", to: "U1.7" },
        { from: "R1.2", to: "R2.1" },
        { from: "R2.2", to: "U1.6" },
        { from: "U1.6", to: "U1.2" },
        { from: "U1.2", to: "C1.+" },
        { from: "C1.-", to: "BT1.NEG" },
        { from: "U1.1", to: "BT1.NEG" },
        { from: "U1.5", to: "C2.1" },
        { from: "C2.2", to: "BT1.NEG" },
        { from: "U1.3", to: "R3.1" },
        { from: "R3.2", to: "LED1.A" },
        { from: "LED1.K", to: "BT1.NEG" },
      ],
    },
  },
  {
    id: "7805-power-supply",
    title: "LM7805 5V Regulated Power Supply",
    prompt: "Create a 5V regulated DC power supply using LM7805 with input/output filter capacitors and reverse polarity protection diode",
    category: "Power & Regulation",
    json: {
      version: "1.0",
      metadata: {
        name: "LM7805 5V Linear Power Supply",
        description: "Regulates 7.5V-15V DC down to clean 5V DC output up to 1A with filtering",
        powerRequirements: "Input: 7.5V-15V DC, Output: 5.0V @ 1.0A max",
        assumptions: ["1N4007 reverse polarity diode on input", "100uF input bulk cap + 10uF output cap"],
      },
      components: [
        {
          id: "J1",
          type: "connector",
          value: "DC Barrel Jack (2.1mm)",
          description: "Unregulated DC Input",
          pins: [
            { id: "TIP", name: "VIN_RAW" },
            { id: "RING", name: "GND" },
          ],
        },
        {
          id: "D1",
          type: "diode",
          value: "1N4007",
          description: "Reverse polarity protection diode",
          pins: [
            { id: "A", name: "Anode" },
            { id: "K", name: "Cathode" },
          ],
        },
        {
          id: "U1",
          type: "ic",
          value: "LM7805CT",
          description: "5V 1A Positive Voltage Regulator (TO-220)",
          pins: [
            { id: "1", name: "IN" },
            { id: "2", name: "GND" },
            { id: "3", name: "OUT" },
          ],
        },
        {
          id: "C1",
          type: "capacitor",
          value: "100uF 25V",
          description: "Input smoothing electrolytic capacitor",
          pins: [
            { id: "+", name: "POS" },
            { id: "-", name: "NEG" },
          ],
        },
        {
          id: "C2",
          type: "capacitor",
          value: "100nF",
          description: "Input high-frequency decoupling ceramic capacitor",
          pins: [
            { id: "1", name: "1" },
            { id: "2", name: "2" },
          ],
        },
        {
          id: "C3",
          type: "capacitor",
          value: "10uF 16V",
          description: "Output stability electrolytic capacitor",
          pins: [
            { id: "+", name: "POS" },
            { id: "-", name: "NEG" },
          ],
        },
        {
          id: "C4",
          type: "capacitor",
          value: "100nF",
          description: "Output ceramic noise bypass",
          pins: [
            { id: "1", name: "1" },
            { id: "2", name: "2" },
          ],
        },
        {
          id: "R1",
          type: "resistor",
          value: "1k",
          description: "5V Power LED current limiter",
          pins: [
            { id: "1", name: "1" },
            { id: "2", name: "2" },
          ],
        },
        {
          id: "LED1",
          type: "led",
          value: "Blue 3mm",
          description: "5V Power Good Indicator",
          pins: [
            { id: "A", name: "Anode" },
            { id: "K", name: "Cathode" },
          ],
        },
        {
          id: "J2",
          type: "connector",
          value: "2-Pin Screw Terminal",
          description: "Clean 5V Output Terminal",
          pins: [
            { id: "1", name: "5V_VCC" },
            { id: "2", name: "GND" },
          ],
        },
      ],
      connections: [
        { from: "J1.TIP", to: "D1.A" },
        { from: "D1.K", to: "U1.1" },
        { from: "D1.K", to: "C1.+" },
        { from: "D1.K", to: "C2.1" },
        { from: "J1.RING", to: "U1.2" },
        { from: "J1.RING", to: "C1.-" },
        { from: "J1.RING", to: "C2.2" },
        { from: "J1.RING", to: "C3.-" },
        { from: "J1.RING", to: "C4.2" },
        { from: "J1.RING", to: "LED1.K" },
        { from: "J1.RING", to: "J2.2" },
        { from: "U1.3", to: "C3.+" },
        { from: "U1.3", to: "C4.1" },
        { from: "U1.3", to: "R1.1" },
        { from: "U1.3", to: "J2.1" },
        { from: "R1.2", to: "LED1.A" },
      ],
    },
  },
  {
    id: "arduino-dht22-oled",
    title: "Arduino Nano + DHT22 & I2C OLED Display",
    prompt: "Arduino Nano reading temperature/humidity from DHT22 on D2 and displaying readings on 0.96 inch SSD1306 OLED via I2C",
    category: "Microcontroller / IoT",
    json: {
      version: "1.0",
      metadata: {
        name: "Arduino Nano Weather Station Hub",
        description: "DHT22 digital environmental sensor with 128x64 I2C monochrome OLED display",
        powerRequirements: "5V via USB or VIN 7-12V",
        assumptions: ["I2C pull-ups internal or module-mounted", "DHT22 data line on Pin D2 with 4.7k pullup"],
      },
      components: [
        {
          id: "U1",
          type: "ic",
          value: "Arduino Nano V3 (ATmega328P)",
          description: "Main 8-bit Microcontroller Board",
          pins: [
            { id: "5V", name: "5V_OUT" },
            { id: "GND", name: "GND" },
            { id: "A4", name: "SDA" },
            { id: "A5", name: "SCL" },
            { id: "D2", name: "GPIO_D2" },
            { id: "VIN", name: "VIN" },
          ],
        },
        {
          id: "U2",
          type: "ic",
          value: "DHT22 / AM2302",
          description: "Digital Temperature & Humidity Sensor",
          pins: [
            { id: "1", name: "VCC" },
            { id: "2", name: "DATA" },
            { id: "3", name: "NC" },
            { id: "4", name: "GND" },
          ],
        },
        {
          id: "R1",
          type: "resistor",
          value: "4.7k",
          description: "DHT22 Data Pull-Up Resistor",
          pins: [
            { id: "1", name: "1" },
            { id: "2", name: "2" },
          ],
        },
        {
          id: "DISP1",
          type: "ic",
          value: "SSD1306 0.96 OLED (128x64)",
          description: "I2C Graphic Display Module",
          pins: [
            { id: "GND", name: "GND" },
            { id: "VCC", name: "VCC" },
            { id: "SCL", name: "SCL" },
            { id: "SDA", name: "SDA" },
          ],
        },
      ],
      connections: [
        { from: "U1.5V", to: "U2.1" },
        { from: "U1.5V", to: "R1.1" },
        { from: "U1.5V", to: "DISP1.VCC" },
        { from: "U1.GND", to: "U2.4" },
        { from: "U1.GND", to: "DISP1.GND" },
        { from: "U1.D2", to: "U2.2" },
        { from: "U2.2", to: "R1.2" },
        { from: "U1.A4", to: "DISP1.SDA" },
        { from: "U1.A5", to: "DISP1.SCL" },
      ],
    },
  },
  {
    id: "esp32-relay-controller",
    title: "ESP32 Optocoupled Relay & Flyback Controller",
    prompt: "ESP32 controlling a 5V SPDT Relay via NPN transistor with flyback diode protection and status LED",
    category: "IoT & Power Switching",
    json: {
      version: "1.0",
      metadata: {
        name: "ESP32 Relay Actuator Module",
        description: "GPIO-driven SPDT relay with 2N2222 transistor driver and 1N4007 flyback suppression",
        powerRequirements: "3.3V Logic / 5V Relay Coil",
        assumptions: ["2N2222 NPN BJT driver with 1k base resistor", "1N4007 antiparallel diode across coil"],
      },
      components: [
        {
          id: "U1",
          type: "ic",
          value: "ESP32 DevKit V1",
          description: "WiFi/BLE Microcontroller Module",
          pins: [
            { id: "3V3", name: "3V3" },
            { id: "GND", name: "GND" },
            { id: "D23", name: "GPIO23_RELAY" },
            { id: "VIN", name: "5V_IN" },
          ],
        },
        {
          id: "Q1",
          type: "transistor",
          value: "2N2222 NPN",
          description: "BJT Low-Side Coil Switch",
          pins: [
            { id: "B", name: "Base" },
            { id: "C", name: "Collector" },
            { id: "E", name: "Emitter" },
          ],
        },
        {
          id: "R1",
          type: "resistor",
          value: "1k",
          description: "Base Current Limiting Resistor",
          pins: [
            { id: "1", name: "1" },
            { id: "2", name: "2" },
          ],
        },
        {
          id: "D1",
          type: "diode",
          value: "1N4007",
          description: "Flyback Clamping Diode",
          pins: [
            { id: "A", name: "Anode" },
            { id: "K", name: "Cathode" },
          ],
        },
        {
          id: "K1",
          type: "switch",
          value: "5V SPDT Relay (10A 250VAC)",
          description: "Electromechanical Power Relay",
          pins: [
            { id: "COIL1", name: "Coil_VCC" },
            { id: "COIL2", name: "Coil_GND" },
            { id: "COM", name: "Common" },
            { id: "NO", name: "Normally_Open" },
            { id: "NC", name: "Normally_Closed" },
          ],
        },
        {
          id: "LED1",
          type: "led",
          value: "Yellow 3mm",
          description: "Relay Energized Indicator",
          pins: [
            { id: "A", name: "Anode" },
            { id: "K", name: "Cathode" },
          ],
        },
        {
          id: "R2",
          type: "resistor",
          value: "470R",
          description: "LED current limiter",
          pins: [
            { id: "1", name: "1" },
            { id: "2", name: "2" },
          ],
        },
      ],
      connections: [
        { from: "U1.D23", to: "R1.1" },
        { from: "R1.2", to: "Q1.B" },
        { from: "Q1.E", to: "U1.GND" },
        { from: "U1.VIN", to: "K1.COIL1" },
        { from: "U1.VIN", to: "D1.K" },
        { from: "U1.VIN", to: "R2.1" },
        { from: "R2.2", to: "LED1.A" },
        { from: "K1.COIL2", to: "Q1.C" },
        { from: "D1.A", to: "Q1.C" },
        { from: "LED1.K", to: "Q1.C" },
      ],
    },
  },
  {
    id: "resistor-led",
    title: "Simple Resistor & LED Indicator",
    prompt: "A simple 1k resistor connected to a red LED powered by 5V and GND",
    category: "Basic Circuits",
    json: {
      version: "1.0",
      metadata: {
        name: "Simple Resistor & LED Indicator",
        description: "Basic current-limiting resistor with LED circuit",
        powerRequirements: "5V DC, ~3mA current draw",
        assumptions: ["Standard Red LED forward voltage 2.0V", "1k Ohm current limiter"],
      },
      components: [
        {
          id: "R1",
          type: "resistor",
          value: "1k",
          description: "Current limiting resistor",
          pins: [
            { id: "1", name: "1" },
            { id: "2", name: "2" },
          ],
        },
        {
          id: "LED1",
          type: "led",
          value: "Red 5mm",
          description: "Visual indicator diode",
          pins: [
            { id: "A", name: "Anode" },
            { id: "K", name: "Cathode" },
          ],
        },
        {
          id: "J1",
          type: "connector",
          value: "2-pin Terminal Block",
          pins: [
            { id: "1", name: "VCC_5V" },
            { id: "2", name: "GND" },
          ],
        },
      ],
      connections: [
        { from: "J1.1", to: "R1.1" },
        { from: "R1.2", to: "LED1.A" },
        { from: "LED1.K", to: "J1.2" },
      ],
    },
  },
];
